// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCthoOBMA9QtXHKScyBmW7NSttaIUNpDCY',
    appId: '1:1011068025232:web:7dd3e306fdbd98ade6db15',
    messagingSenderId: '1011068025232',
    projectId: 'crud-f8ff0',
    authDomain: 'crud-f8ff0.firebaseapp.com',
    storageBucket: 'crud-f8ff0.firebasestorage.app',
    measurementId: 'G-GNL1HLMME6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeigyH-Spp66HqYt2el0iwCYQVc_KWRnw',
    appId: '1:1011068025232:android:b1facac501c1e160e6db15',
    messagingSenderId: '1011068025232',
    projectId: 'crud-f8ff0',
    storageBucket: 'crud-f8ff0.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0DGD1pwn8oiKhgzklvCkPlyFpayk6DPM',
    appId: '1:1011068025232:ios:b27829f446804274e6db15',
    messagingSenderId: '1011068025232',
    projectId: 'crud-f8ff0',
    storageBucket: 'crud-f8ff0.firebasestorage.app',
    iosClientId: '1011068025232-2ovl2q72m1ro29lfbpgmtgla5qupnu5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.elitetraders',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0DGD1pwn8oiKhgzklvCkPlyFpayk6DPM',
    appId: '1:1011068025232:ios:b27829f446804274e6db15',
    messagingSenderId: '1011068025232',
    projectId: 'crud-f8ff0',
    storageBucket: 'crud-f8ff0.firebasestorage.app',
    iosClientId: '1011068025232-2ovl2q72m1ro29lfbpgmtgla5qupnu5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.elitetraders',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCthoOBMA9QtXHKScyBmW7NSttaIUNpDCY',
    appId: '1:1011068025232:web:818e6e544d63ea7ee6db15',
    messagingSenderId: '1011068025232',
    projectId: 'crud-f8ff0',
    authDomain: 'crud-f8ff0.firebaseapp.com',
    storageBucket: 'crud-f8ff0.firebasestorage.app',
    measurementId: 'G-BKDC2KLP8Z',
  );

}